        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:40 2015
        MODULE GLOBAL_UPDATE_mod
          INTERFACE 
            SUBROUTINE GLOBAL_UPDATE
          END SUBROUTINE GLOBAL_UPDATE
        END INTERFACE 
      END MODULE GLOBAL_UPDATE_mod
