        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:35 2015
        MODULE GRAPH_DETAILS_mod
          INTERFACE 
            SUBROUTINE GRAPH_DETAILS(NUM_DECISION_PTS,NUM_EDGES)
            INTEGER(KIND=4) :: NUM_DECISION_PTS
            INTEGER(KIND=4) :: NUM_EDGES(N_YEARS*N_COUNTRIES*N_COUNTRIES&
     &)
          END SUBROUTINE GRAPH_DETAILS
        END INTERFACE 
      END MODULE GRAPH_DETAILS_mod
