        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:36 2015
        MODULE INITIAL_TAU_mod
          INTERFACE 
            SUBROUTINE INITIAL_TAU
            END SUBROUTINE INITIAL_TAU
          END INTERFACE 
        END MODULE INITIAL_TAU_mod
