        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:37 2015
        MODULE INITIALISE_ANT_GRAPH_mod
          INTERFACE 
            SUBROUTINE INITIALISE_ANT_GRAPH
            END SUBROUTINE INITIALISE_ANT_GRAPH
          END INTERFACE 
        END MODULE INITIALISE_ANT_GRAPH_mod
