        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:37 2015
        MODULE INITIALISE_PACO_PARAMETERS_mod
          INTERFACE 
            SUBROUTINE INITIALISE_PACO_PARAMETERS
            END SUBROUTINE INITIALISE_PACO_PARAMETERS
          END INTERFACE 
        END MODULE INITIALISE_PACO_PARAMETERS_mod
