        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:35 2015
        MODULE LOCAL_UPDATE_mod
          INTERFACE 
            SUBROUTINE LOCAL_UPDATE(I,J)
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: J
            END SUBROUTINE LOCAL_UPDATE
          END INTERFACE 
        END MODULE LOCAL_UPDATE_mod
