        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:37 2015
        MODULE NON_DOM_SORT_mod
          INTERFACE 
            SUBROUTINE NON_DOM_SORT
            END SUBROUTINE NON_DOM_SORT
          END INTERFACE 
        END MODULE NON_DOM_SORT_mod
