        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:37 2015
        MODULE NON_DOM_SORT2_mod
          INTERFACE 
            SUBROUTINE NON_DOM_SORT2
            END SUBROUTINE NON_DOM_SORT2
          END INTERFACE 
        END MODULE NON_DOM_SORT2_mod
