        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:39 2015
        MODULE PROB_DETERMINATION_mod
          INTERFACE 
            SUBROUTINE PROB_DETERMINATION(I,J)
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: J
            END SUBROUTINE PROB_DETERMINATION
          END INTERFACE 
        END MODULE PROB_DETERMINATION_mod
