        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:40 2015
        MODULE STORAGE_UPDATE_mod
          INTERFACE 
            SUBROUTINE STORAGE_UPDATE(X,J)
              INTEGER(KIND=4) :: X
              INTEGER(KIND=4) :: J
            END SUBROUTINE STORAGE_UPDATE
          END INTERFACE 
        END MODULE STORAGE_UPDATE_mod
