        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 19 15:49:36 2015
        MODULE TRADE_CONSTRAINT_mod
          INTERFACE 
            SUBROUTINE TRADE_CONSTRAINT(X,J)
              INTEGER(KIND=4) :: X
              INTEGER(KIND=4) :: J
            END SUBROUTINE TRADE_CONSTRAINT
          END INTERFACE 
        END MODULE TRADE_CONSTRAINT_mod
